---
Name: otagocontentreviewextensions
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - OP\ContentReview\Extensions\ContentReviewLeftAndMainExtension
SilverStripe\CMS\Controllers\CMSPageEditController:
  extensions:
    - OP\ContentReview\Extensions\ContentReviewCMSExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - OP\ContentReview\Extensions\ContentReviewDefaultSettings
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - OP\ContentReview\Extensions\SiteTreeContentReview
# apply ContentReviewGroups
SilverStripe\Security\Group:
  extensions:
    - OP\ContentReview\Extensions\ContentReviewOwner
# apply ContentReviewUsers
SilverStripe\Security\Member:
  extensions:
    - OP\ContentReview\Extensions\ContentReviewOwner
